### ISSUE TITLE
Kogito overwrites Enum variable when we use task with isAsync

### ISSUE THREAD

**Issue by Dantes-Damir** [apache/incubator-kie-examples#1115]
I dowloaded process-postgresql-persistence-springboot https://github.com/kiegroup/kogito-examples/tree/stable/kogito-springboot-examples/process-postgresql-persistence-springboot and made some changes:
I created enum:
`public enum LogEntityType {
    REQUEST,
    RESPONSE,
    STRAT_PARAMS,
    AUTO_ANSWER
}`

Then I added "private LogEntityType logEntityType;" in Traveller class:
`package org.acme.deals;

public class Traveller {

    private String firstName;
    private String lastName;
    private String email;
    private String nationality;
    private Address address;
    private LogEntityType logEntityType;

    public Traveller() {
        System.out.println("Call empty constructor");
        this.logEntityType = LogEntityType.REQUEST;
    }

    public Traveller(String firstName, String lastName, String email, String nationality, Address address) {
        System.out.println("Call full constructor");
        this.logEntityType = LogEntityType.REQUEST;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.nationality = nationality;
        this.address = address;
    }

    public LogEntityType getLogEntityType() {
        return logEntityType;
    }

    public void setLogEntityType(LogEntityType logEntityType) {
        System.out.println("Call setter LogEntityType: " + logEntityType.name());
        this.logEntityType = logEntityType;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getNationality() {
        return nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    @Override
    public String toString() {
        return "Traveller [firstName=" + firstName + ", lastName=" + lastName + ", email=" + email + ", nationality=" + nationality + ", address=" + address + "]";
    }

}`

Then i created class:
`
package org.acme.deals;
import org.springframework.stereotype.Component;

@Component
public class ServiceTask {
    public void execute(Traveller traveller) {
        System.out.println("Execute LogEntityType: " + traveller.getLogEntityType());
    }
}`
Then i edited SubmitDeal.bpmn. I just added one service task:
![submitDeal](https://user-images.githubusercontent.com/10437921/152307543-02c75737-fcff-4ba4-9869-f86202b067a5.png)
![submitDealInput](https://user-images.githubusercontent.com/10437921/152307563-d565b841-6c92-4fae-a9ba-32d81b7bca1c.png)

And after sending request i got the logs:
[logs (2).txt](https://github.com/kiegroup/kogito-examples/files/7992966/logs.2.txt)

Why Kogito calls setter and overwrites logEntityType variable value from Request to AUTO_ANSWER?

**Comment by fjtirado** [comment]
@cristianonicolai the call to setLogEntity that appears in the log is probably performed during unmarshalling (when the process info is read as part of persistence addon) 
@Dantes-Damir in the meantine, can you print the stack trace in setLogEntity to confirm that?

**Comment by Dantes-Damir** [comment]
@fjtirado java.lang.Throwable
	at org.acme.deals.Traveller.setLogEntityType(Traveller.java:48)
	at org.kie.kogito.app.TravellerMessageMarshaller.readFrom(TravellerMessageMarshaller.java:37)
	at org.kie.kogito.app.TravellerMessageMarshaller.readFrom(TravellerMessageMarshaller.java:21)
	at org.infinispan.protostream.impl.MessageMarshallerDelegate.unmarshall(MessageMarshallerDelegate.java:96)
	at org.infinispan.protostream.ProtobufUtil.readFrom(ProtobufUtil.java:95)
	at org.infinispan.protostream.ProtobufUtil.fromByteArray(ProtobufUtil.java:108)
	at org.kie.kogito.persistence.ProtostreamObjectMarshaller.unmarshall(ProtostreamObjectMarshaller.java:69)
	at org.kie.kogito.serialization.process.impl.ProtobufVariableReader.buildVariables(ProtobufVariableReader.java:44)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.buildWorkflow(ProtobufProcessInstanceReader.java:178)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceReader.read(ProtobufProcessInstanceReader.java:115)
	at org.kie.kogito.serialization.process.impl.ProtobufProcessInstanceMarshaller.readProcessInstance(ProtobufProcessInstanceMarshaller.java:47)
	at org.kie.kogito.serialization.process.ProcessInstanceMarshallerService.unmarshallProcessInstance(ProcessInstanceMarshallerService.java:122)
	at org.kie.kogito.serialization.process.ProcessInstanceMarshallerService.unmarshallProcessInstance(ProcessInstanceMarshallerService.java:129)
	at org.kie.kogito.persistence.jdbc.JDBCProcessInstances.findById(JDBCProcessInstances.java:121)
	at org.kie.kogito.process.ProcessInstances.findById(ProcessInstances.java:24)
	at org.kie.services.jobs.impl.TriggerJobCommand.lambda$execute$1(TriggerJobCommand.java:47)
	at org.kie.kogito.services.uow.UnitOfWorkExecutor.executeInUnitOfWork(UnitOfWorkExecutor.java:33)
	at org.kie.services.jobs.impl.TriggerJobCommand.execute(TriggerJobCommand.java:46)
	at org.kie.services.jobs.impl.InMemoryJobService$SignalProcessInstanceOnExpiredTimer.run(InMemoryJobService.java:161)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
