### ISSUE TITLE
IllegalStateException: Unable to perform hot replacement scanning

### ISSUE THREAD

**Issue by jmini** [apache/incubator-kie-examples#124]
When the `jbpm-quarkus-example` is started in dev mode with:

```
mvn clean package quarkus:dev
```
As indicated in the Readme.

I sometimes get this error on pages like http://localhost:8080/swagger-ui/ or in the return statement of a REST request:

*Error restarting Quarkus*
```
java.lang.IllegalStateException: Unable to perform hot replacement scanning
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:53)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:43)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.UncheckedIOException: java.nio.file.DirectoryNotEmptyException: /<path-to>/kogito-examples/jbpm-quarkus-example/target/classes/META-INF/resources
	at io.quarkus.dev.RuntimeUpdatesProcessor.checkForFileChange(RuntimeUpdatesProcessor.java:376)
	at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:124)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:51)
	... 6 more
Caused by: java.nio.file.DirectoryNotEmptyException: /<path-to>/kogito-examples/jbpm-quarkus-example/target/classes/META-INF/resources
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at io.quarkus.dev.RuntimeUpdatesProcessor.checkForFileChange(RuntimeUpdatesProcessor.java:374)
	... 8 more
```

This can be manually fixed by running:

```
rm -R /<path-to>/kogito-examples/jbpm-quarkus-example/target/classes/META-INF/resources
```

... before reloading the page.

But I assume that this is not the idea.

**Comment by evacchi** [comment]
a change in quarkus causes `mvn clean package quarkus:dev` not to work
you should use `mvn clean compile quarkus:dev` we are investigating to understand what causes the issue

**Comment by jomarko** [comment]
The same happens also in https://github.com/kiegroup/kogito-examples/blob/master/onboarding-example/

**Comment by jomarko** [comment]
![Screenshot from 2020-02-05 09-08-56](https://user-images.githubusercontent.com/8044780/73822797-2ca92c00-47f7-11ea-85e1-44296f6d4e14.png)

@evacchi this is what I see when using `mvn clean compile quarkus:dev` is that expected. I am confused as endpoints are listed but header says 404 - not found.

**Comment by r00ta** [comment]
Hi @jomarko , atm `mvn clean compile quarkus:dev` works properly on those projects. I will close the issue but if you still have some problems with those feel free to re-open
