### ISSUE TITLE
[process-kafka-quickstart-quarkus] Error connecting to node kafka:9092 (id: 0 rack: null): java.net.UnknownHostException: 不知道这样的主机。 (kafka)

### ISSUE THREAD

**Issue by leesonwei** [apache/incubator-kie-examples#1589]
### Describe the bug

`2023-02-28 21:34:32,192 WARN  [org.apa.kaf.cli.NetworkClient] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-travellers, groupId=kogito-kafka-one] Error connecting to node kafka:9092 (id: 0 rack: null): java.net.UnknownHostException: 不知道这样的主机。 (kafka)
        at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:933)
        at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1519)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:852)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1367)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1301)
        at org.apache.kafka.clients.DefaultHostResolver.resolve(DefaultHostResolver.java:27)
        at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:110)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:510)
        at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:467)
        at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:173)
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:990)
        at org.apache.kafka.clients.NetworkClient.access$600(NetworkClient.java:73)
        at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1163)
        at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1051)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:558)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:280)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:251)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
        at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:164)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:277)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureCoordinatorReady(AbstractCoordinator.java:240)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.coordinatorUnknownAndUnreadySync(ConsumerCoordinator.java:492)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:524)
        at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1276)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1240)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1220)
        at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaConsumer.lambda$poll$4(ReactiveKafkaConsumer.java:156)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:36)
        at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:47)
        at io.smallrye.mutiny.operators.uni.UniMemoizeOp.subscribe(UniMemoizeOp.java:73)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
`

### How to Reproduce?

1. add `quarkus.devservices.enabled=false` to application.properties
2. cd process-kafka-quickstart-quarkus
3. mvn clean compile quarkus:dev

### Output of `uname -a` or `ver`

win10

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

1.33.1-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7

**Comment by radtriste** [comment]
If you disable the devservices, then no Kafka will be started by quarkus in dev mode. Thus it cannot find any Kafka instance.
Unless you started one on your local ?

**Comment by leesonwei** [comment]
> If you disable the devservices, then no Kafka will be started by quarkus in dev mode. Thus it cannot find any Kafka instance. Unless you started one on your local ?

thank you for the response. Sorry, supplementary instruction: I've run a kafka instance locally, and I see that the connection message is successful, as follows. 
`2023-02-28 22:59:58,359 INFO  [io.sma.rea.mes.kafka] (smallrye-kafka-producer-thread-0) SRMSG18258: Kafka producer kafka-producer-kogito_outgoing_stream, connected to Kafka brokers 'localhost:9092', is configured to write records to 'processedtravellers'
2023-02-28 22:59:58,407 INFO  [io.sma.rea.mes.kafka] (smallrye-kafka-consumer-thread-0) SRMSG18257: Kafka consumer kafka-consumer-travellers, connected to Kafka brokers 'localhost:9092', belongs to the 'kogito-kafka-one' consumer group and is configured to poll records from [travellers]
2023-02-28 22:59:58,475 INFO  [org.kie.kog.eve.imp.AbstractMessageConsumer] (Quarkus Main Thread) Consumer for travellers started
`
When I start a process instance, kafka will not link from the localhost:9092 I configured in application.properties, but will link from kafka:9092

**Comment by radtriste** [comment]
@cristianonicolai or @nmirasch will be more able to answer that one

**Comment by fjtirado** [comment]
@leesonwei you need to add to application.properties kafka.bootstrap.servers=localhost:9092

**Comment by leesonwei** [comment]
> @leesonwei you need to add to application.properties kafka.bootstrap.servers=localhost:9092

yes, I do add this config item. it work at startup and fail by start a process instance
