### ISSUE TITLE
process-quarkus-example build failure: class not found CalculationService

### ISSUE THREAD

**Issue by JeannedArk** [apache/incubator-kie-examples#1662]
### Describe the bug

There is a build error when starting the dev service:

> 2023-05-05 16:55:21,890 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (vert.x-worker-thread-1) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateSources threw an exception: org.kie.kogito.codegen.process.ProcessCodegenException: Error while elaborating process id = "demo.orderItems", packageName = "org.kie.kogito.examples": Invalid work item "Calculate total": class not found for interfaceName "CalculationService"
        at org.kie.kogito.codegen.process.ProcessCodegen.internalGenerate(ProcessCodegen.java:333)
        at org.kie.kogito.codegen.core.AbstractGenerator.generate(AbstractGenerator.java:69)
        at org.kie.kogito.codegen.core.ApplicationGenerator.lambda$generateComponents$0(ApplicationGenerator.java:95)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at org.kie.kogito.codegen.core.ApplicationGenerator.generateComponents(ApplicationGenerator.java:97)
        at org.kie.kogito.codegen.core.ApplicationGenerator.generate(ApplicationGenerator.java:74)
        at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateFiles(KogitoAssetsProcessor.java:264)
        at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateSources(KogitoAssetsProcessor.java:141)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:1623)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.IllegalArgumentException: Invalid work item "Calculate total": class not found for interfaceName "CalculationService"
        at org.jbpm.compiler.canonical.descriptors.ServiceTaskDescriptor.<init>(ServiceTaskDescriptor.java:90)
        at org.jbpm.compiler.canonical.descriptors.TaskDescriptorBuilder.build(TaskDescriptorBuilder.java:75)
        at org.jbpm.compiler.canonical.WorkItemNodeVisitor.visitNode(WorkItemNodeVisitor.java:93)
        at org.jbpm.compiler.canonical.WorkItemNodeVisitor.visitNode(WorkItemNodeVisitor.java:42)
        at org.jbpm.compiler.canonical.AbstractNodeVisitor.visitNode(AbstractNodeVisitor.java:76)
        at org.jbpm.compiler.canonical.ProcessVisitor.visitNodes(ProcessVisitor.java:220)
        at org.jbpm.compiler.canonical.ProcessVisitor.visitProcess(ProcessVisitor.java:174)
        at org.jbpm.compiler.canonical.ProcessToExecModelGenerator.generate(ProcessToExecModelGenerator.java:100)
        at org.kie.kogito.codegen.process.ProcessExecutableModelGenerator.generate(ProcessExecutableModelGenerator.java:44)
        at org.kie.kogito.codegen.process.ProcessCodegen.internalGenerate(ProcessCodegen.java:329)
        ... 22 more

Example from the latest stable branch: https://github.com/kiegroup/kogito-examples/tree/stable/kogito-quarkus-examples/process-quarkus-example

### Expected behavior

Working service without build errors

### Actual behavior

Service is not working. Accessing `http://0.0.0.0:8080/` results in an error page:
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors

### How to Reproduce?

Follow the readme and run maven:
```bash
cd /kogito-examples/kogito-quarkus-examples/process-quarkus-example
mvn clean compile quarkus:dev
```

### Output of `uname -a` or `ver`

Darwin MBP 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.4.1" 2022-08-12

### Kogito version or git rev (or at least Quarkus version if you are using Kogito via Quarkus platform BOM)

baea2028834241a75535bf2da053d6c7da23188a

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)

**Comment by fjtirado** [comment]
Tested with apache maven 3.9.0. 
It is working fine. 
Can you try with main branch rather than stable?

**Comment by JeannedArk** [comment]
Switching to the main branch works and then switching back to the stable worked for me then too. A bit weird, maybe there was a dependency update meanwhile. It is working now so I close the issue.
